local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Jenga", "Synapse")
local Tab = Window:NewTab("Main")
local Section = Tab:NewSection("Scripts")
Section:NewButton("Teleport Destroyer", "idk", function()
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(235,100,25)
end)
Section:NewButton("EndGame", "for towers", function()
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-65,100,-19)
end)
Section:NewButton("Teleport Towers", "idk", function()
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-67,228,-22)
end)
